services:
#Remove ports for internal services; it's not necessary to expose them.
# Only expose ports if external testing or access to specific microservices is needed
  mcsv-config:
    container_name: mcsv-config
    build:
      context: ./mcsv-config
      dockerfile: Dockerfile
    networks:
      - config-network
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:8889/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 10

  mcsv-eureka:
    container_name: mcsv-eureka
    build:
      context: ./mcsv-eureka
      dockerfile: Dockerfile
    ports:
      #host_port:container_port
      - "8761:8761" # if the app runs on 8761 internally
    networks:
      - config-network
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mcsv-config:
        condition: service_healthy

  mcsv-auth:
    container_name: mcsv-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - config-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mcsv-eureka:
        condition: service_healthy

  mcsv-websocket:
    container_name: mcsv-websocket
    build:
      context: ./mcsv-websocket
      dockerfile: Dockerfile
    networks:
      - config-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mcsv-eureka:
        condition: service_healthy

  mcsv-message:
    container_name: mcsv-message
    build:
      context: ./mcsv-message
      dockerfile: Dockerfile
    networks:
      - config-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      mcsv-eureka:
        condition: service_healthy

  mcsv-gateway:
    container_name: mcsv-gateway
    build:
      context: ./mcsv-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - config-network
    depends_on:
      mcsv-auth:
        condition: service_healthy
      mcsv-websocket:
        condition: service_healthy
      mcsv-message:
        condition: service_healthy

networks:
  config-network:
    driver: bridge