server:
  port: 8888
  servlet:
    context-path: /
spring:
  profiles:
    # Tells Spring to use the native file system or classpath instead of Git.
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      # Suppress UNKNOWN warnings for optional components like Config Server or Discovery
      failFast: false
#To use actuator and "depends on"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
