server:
  port: 8090

spring:
  application:
    name: mcsv-websocket
  #Spring level to define beans will be used throughout the service
  kafka:

  cassandra:
    keyspace-name: CHAT
    contact-points: 127.0.0.1
    port: 9042
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
        # Auto-creates tables from your @Table entities

management:
  endpoints:
    web:
      exposure:
        include: health

#Eureka connection
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
