server:
  port: 8090

spring:
  application:
    name: mcsv-websocket
  #Spring level to define beans will be used throughout the service
  kafka:

management:
  endpoints:
    web:
      exposure:
        include: health

#Eureka connection
eureka:
  client:
    service-url:
      defaultZone: http://mcsv-eureka:8761/eureka/
