server:
  port: 8761

spring:
  application:
    name: mcsv-eureka

#Connecting to eureka
eureka:
  instance:
    hostname: mcsv-eureka  # Use container name, not "localhost"
    prefer-ip-address: true  # Optional: useful in Docker
  client:
    #Disable autosave eureka within its own server
    register-with-eureka: false
    fetch-registry: false
    #Path of eureka server
    service-url:
      defaultZone: http://mcsv-eureka:${server.port}/eureka/ # Ensure `service-url`, not `server-url`

#exposes the /actuator/health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health