server:
  port: 8050

spring:
  application:
    name: mcsv-message

  cassandra:
    keyspace-name: CHAT
    contact-points: 127.0.0.1
    port: 9042
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1

management:
  endpoints:
    web:
      exposure:
        include: health

#Eureka configuration—Connecting to it
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/