server:
  port: 8080

spring:
  application:
    name: mcsv-gateway

  cloud:
    gateway:
      websockets:
        enabled: true  # 👈 Enable WebSocket support

      discovery:
        locator:
          #Equivalent to use the annotation "@EnableDiscoveryClient"
          #discovery locator allows the gateway to dynamically discover services registered with a service registry(eureka) instead using PORTS or ip addresses
          enabled: true
      #Gateway checks all routes(predicates) and if it finds the coincidence, it forwards to the respective uri(microservice)
      routes:
        - id: chat
          #Names defined in those application names,which is registered in the eureka server(should be the same)
          uri: lb://MCSV-WEBSOCKET
          predicates:
          #If the request matches this route, re request is redirected(forwards) to the respective service defined in the uri
            - Path=/api/websocket/**
          filters:
            - AuthenticationFilter
        #Diferents rules for the same service
        - id: websocket
          uri: lb://MCSV-WEBSOCKET
          predicates:
            - Path=/websocket
          filters:
            #Modifies the incoming request path before forwarding to the microservice
            #Basically changing the path to matches it with the websocket endpoint (this case doesn't anything)
            - name: RewritePath
              args:
                #
                regexp: /websocket
                replacement: /websocket

        - id: auth
          #Names defined in those application names
          uri: lb://MCSV-AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            discovery: TRACE
            route: TRACE
            filter: TRACE